paths:
  input:
    input_data: /example/path/dataset/input_dataset
    evol: /example/path/dataset/input_dataset/Anonymized_PDF_Progress_Notes
    discharge: /example/path/dataset/input_dataset/Anonymized_PDF_Discharge_Reports
    anamnesis: /example/path/dataset/input_dataset/Anonymized_PDF_Anamnesis_Sheets
    abbreviations_extractor: /example/path/models/abbreviations_extractor/final_model
    medications_extractor: /example/path/models/medications_extractor/final_model
    medications_finetune_prompt: /example/path/prompts/prompt_finetuning_medications.txt
    abbreviations_finetune_prompt: /example/path/prompts/prompt_finetuning_terms.txt
    abbreviations: /example/path/dataset/abbreviations_merged.csv
    medications: /example/path/dataset/medications.json
  output:
    preprocessed_admissions: /example/path/dataset/output_dataset/preprocessed/Admissions
    output_data: /example/path/dataset/output_dataset/
    results_name: llama_1b_improved
model:
  name: llama
  type: 1b # gpt-3.5-turbo-1106
  api_key: sk-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
  policy: sectioned # Can be "sectioned" or "complete"

