gpt-4o:
  input: 5.00
  output: 15.00
gpt-4o-2024-05-13:
  input: 5.00
  output: 15.00
gpt-4-turbo:
  input: 10.00
  output: 30.00
gpt-4-turbo-2024-04-09:
  input: 10.00
  output: 30.00
gpt-4:
  input: 30.00
  output: 60.00
gpt-4-32k:
  input: 60.00
  output: 120.00
gpt-3.5-turbo-0125:
  input: 0.50
  output: 1.50
gpt-3.5-turbo-instruct:
  input: 1.50
  output: 2.00
gpt-3.5-turbo:
  input: 8.00
  output: 6.00
davinci-002:
  input: 6.00
  output: 12.00
babbage-002:
  input: 0.40
  output: 1.60
gpt-4-0125-preview:
  input: 10.00
  output: 30.00
gpt-4-1106-preview:
  input: 10.00
  output: 30.00
gpt-4-vision-preview:
  input: 10.00
  output: 30.00
gpt-3.5-turbo-1106:
  input: 1.00
  output: 2.00
gpt-3.5-turbo-0613:
  input: 1.50
  output: 2.00
gpt-3.5-turbo-16k-0613:
  input: 3.00
  output: 4.00
gpt-3.5-turbo-0301:
  input: 1.50
  output: 2.00